# face_netd v1 config
# 修改 mqtt_url 为电脑服务器地址

device_id = k230-dev-01
mqtt_url = mqtt://192.168.160.8:1883
mqtt_client_id = face-netd-k230-dev-01
mqtt_username =
mqtt_password =
heartbeat_interval_ms = 5000
ipc_connect_retry_ms = 500
ipc_sync_timeout_ms = 3000
mqtt_keepalive_s = 15
